# Generated by Django 6.0 on 2025-12-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
