# Generated by Django 6.0 on 2025-12-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_bicicleta_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_hora_reserva',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
