# Generated by Django 6.0 on 2025-12-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_vaga_remove_perfil_curso_remove_perfil_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='bicicleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.bicicleta'),
        ),
    ]
