# Generated by Django 6.0 on 2025-12-11 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_alter_reserva_bicicleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_usuarios.vaga'),
        ),
    ]
